export type ApplicationErrorCode =
  | "VALIDATION_ERROR"
  | "REQUEST_BODY_TOO_LARGE"
  | "UNSUPPORTED_MEDIA_TYPE"
  | "ORIGIN_NOT_ALLOWED"
  | "RATE_LIMITED"
  | "IDEMPOTENCY_KEY_INVALID"
  | "IDEMPOTENCY_KEY_REUSED"
  | "IDEMPOTENCY_IN_PROGRESS"
  | "CONCURRENT_MUTATION"
  | "TASK_NOT_FOUND"
  | "TASK_ALREADY_EXECUTED"
  | "TASK_NOT_ACTIVE"
  | "INVALID_TASK_TRANSITION"
  | "POLICY_NOT_FOUND"
  | "POLICY_ARCHIVED"
  | "PROVIDER_NOT_FOUND"
  | "PROVIDER_ID_TAKEN"
  | "PROVIDER_DISABLED"
  | "PROVIDER_UNHEALTHY"
  | "PROVIDER_MODE_MISMATCH"
  | "PROVIDER_MODE_UNSUPPORTED"
  | "PROVIDER_RUNTIME_NOT_CONNECTED"
  | "PROVIDER_EXECUTION_FAILED"
  | "PROVIDER_ENDPOINT_INVALID"
  | "PROVIDER_ENDPOINT_INSECURE"
  | "PROVIDER_ENDPOINT_BLOCKED"
  | "PROVIDER_HTTP_UNHEALTHY"
  | "PROVIDER_NETWORK_MISMATCH"
  | "PROVIDER_ASSET_MISMATCH"
  | "PROVIDER_SECRET_KEY_NOT_CONFIGURED"
  | "PROVIDER_SECRET_KEY_INVALID"
  | "PROVIDER_CREDENTIAL_INVALID"
  | "PROVIDER_CREDENTIAL_DECRYPT_FAILED"
  | "X402_EXPECTED_PAYMENT_REQUIRED"
  | "X402_CHALLENGE_MISSING"
  | "X402_CHALLENGE_INVALID"
  | "MPP_EXPECTED_PAYMENT_REQUIRED"
  | "MPP_CHALLENGE_MISSING"
  | "CHANNEL_NOT_FOUND"
  | "CHANNEL_NOT_READY"
  | "CHANNEL_NETWORK_MISMATCH"
  | "CHANNEL_RECOVERY_REQUIRED"
  | "CHANNEL_ACTION_NOT_ALLOWED"
  | "CHANNEL_FINALIZATION_AMBIGUOUS"
  | "LIVE_SANDBOX_BUDGET_EXCEEDED"
  | "LIVE_CHANNELS_NOT_OPEN"
  | "LIVE_CHANNEL_MODE_REQUIRED"
  | "LIVE_CHANNEL_NOT_PREPARED"
  | "LIVE_CHANNEL_OPEN_EVIDENCE_MISSING"
  | "LIVE_TASK_NOT_EXECUTED"
  | "SETTINGS_ENVIRONMENT_NETWORK_MISMATCH"
  | "SETTINGS_EXPLORER_NETWORK_MISMATCH"
  | "MAINNET_ACKNOWLEDGEMENT_REQUIRED"
  | "MAINNET_ASSET_MINT_REQUIRED"
  | "MAINNET_DEMO_MODE_BLOCKED"
  | "MAINNET_DEMO_PROVIDER_BLOCKED"
  | "MAINNET_ENDPOINT_INSECURE"
  | "MAINNET_RUNTIME_NOT_CONFIGURED"
  | "LOCAL_RUNTIME_MODE_UNAVAILABLE"
  | "DEFAULT_POLICY_INVALID"
  | "INTEGRATION_PROTOCOL_UNSUPPORTED"
  | "INTEGRATION_CONNECTION_FAILED"
  | "INTEGRATION_NETWORK_MISMATCH"
  | "INTEGRATION_ASSET_MISMATCH"
  | "TASK_NETWORK_MISMATCH"
  | "TASK_ASSET_MISMATCH"
  | "DEVELOPER_SECRET_NOT_CONFIGURED"
  | "DEVELOPER_SECRET_INVALID"
  | "API_KEY_REQUIRED"
  | "API_KEY_INVALID"
  | "API_KEY_SCOPE_REQUIRED"
  | "API_KEY_NOT_FOUND"
  | "SANDBOX_MAINNET_BLOCKED"
  | "SANDBOX_MODE_UNAVAILABLE"
  | "WEBHOOK_SECRET_INVALID"
  | "WEBHOOK_URL_INVALID"
  | "WEBHOOK_URL_INSECURE"
  | "WEBHOOK_URL_BLOCKED"
  | "WEBHOOK_NOT_FOUND"
  | "WEBHOOK_DELIVERY_NOT_FOUND"
  | "STORAGE_NOT_CONFIGURED"
  | "STORAGE_ERROR"
  | "AUTH_REQUIRED"
  | "AUTH_CHALLENGE_NOT_FOUND"
  | "AUTH_CHALLENGE_EXPIRED"
  | "AUTH_CHALLENGE_USED"
  | "AUTH_WALLET_MISMATCH"
  | "AUTH_SIGNATURE_INVALID"
  | "FORBIDDEN";

export class ApplicationError extends Error {
  constructor(
    readonly code: ApplicationErrorCode,
    message: string,
    readonly status: number,
    readonly details?: unknown,
  ) {
    super(message);
    this.name = "ApplicationError";
  }
}

export type ApiErrorEnvelope = {
  error: {
    code: ApplicationErrorCode | "INTERNAL_ERROR";
    message: string;
    details?: unknown;
  };
};
